# Generated by Django 5.2.7 on 2025-10-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tag_blog_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='vote_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
